### ISSUE TITLE
support requirejs setup

### ISSUE THREAD

**Issue by khanhlu2013** [nolanlawson/pouchdb-quick-search#12]
As the doc said, to setup this library in the browser (vs in node.js)  we include 2 script tags: one for pouchdb and one for pouchdb-quick-search in that order.The first script tag attach PouchDB to the window object. the second script tag look for window.PouchDB to register the plugin: window.PouchDB.plugin(exports);

Requirejs does not attach PouchDB to window object. Consequently, pouchdb-quick-search can not  be registered as a plugin. Any suggestion?

**Comment by snehilmodani** [comment]
@khanhlu2013 did you find a way around?

**Comment by snehilmodani** [comment]
I did find a way around it. We just need to build the plugin again like it is mentioned in this issue.
https://github.com/nolanlawson/pouchdb-all-dbs/issues/12
