### ISSUE TITLE
is it possible to get all docs by passing empty query ?

### ISSUE THREAD

**Issue by chandu0101** [nolanlawson/pouchdb-quick-search#24]
I want to get all docs by passing empty query ``""``  . Is it possible .. ?

**Comment by nolanlawson** [comment]
If you just want to fetch all the docs, you can use `allDocs()`. :)

**Comment by chandu0101** [comment]
hmm , i can use that but why it's not possible from this plugin! could you please explain ..

**Comment by nolanlawson** [comment]
This plugin doesn't try to solve every possible PouchDB problem. :) E.g. see the section on autocomplete/prefix search.

**Comment by chandu0101** [comment]
The reason i am asking this because when my search box changes i want to fire db.search without checking it's empty or not :)  . Just out of curiosity is there any API  in pouchdb world that i can use to search and retrieve all docs ..

**Comment by nolanlawson** [comment]
Yes, you want to use `db.allDocs()`: http://pouchdb.com/api.html#batch_fetch

**Comment by chandu0101** [comment]
hmm , i want to search in multiple fields . is it harder to implement in quick search plugin ? could you please throw some light on this .. ,I'll see if i can make a patch! ( I need this badly for my specific use case)

**Comment by nolanlawson** [comment]
I'm not really sure what the issue is... why isn't `allDocs` working for you?

**Comment by chandu0101** [comment]
hmm ok let me explain , i have db with the following doc structure ..
```js
{ title : "Title1" ,description : "Description1" ,category : "cat1" , _id : date created }
{ title : "Title1" ,description : "Description1" ,category : "cat2"  ,_id : date created}
{ title : "Title1" ,description : "Description1" ,category : "cat3"  ,_id : date created}
{ title : "Title1" ,description : "Description1" ,category : "cat4"  ,_id : date created}
```

In my app i have different pages for different categories , each page should support searching (both title and description) and pagination . 

for this requirement search API is apt because it supports 

filter -> so that i can pic specific category
limit,skip -> pagination
query  -> search docs

allDocs is out of scope because it doesn't support pagination with filter! ( or am i missing something here ...)
may be i have to use db.query , but again if its possible in quick search my app code will be simple to reason about and maintain ..

**Comment by nolanlawson** [comment]
`allDocs` supports pagination, but only when sorting/filtering by `_id`. However, I'm not sure why you can't use pouchdb-quick-search to put an index on `cat` and then `search()` that?

Alternatively, you could look into [pouchdb-find](http://nolanlawson.github.io/pouchdb-find/), which is a simpler replacement for `query()`. You have many options. :)

**Comment by chandu0101** [comment]
yeah the best option out there is db.find , but it'll add more 50kb! . I think i have to stop overthinking and start coding with db.find :) . thanks for your replies :)

**Comment by nolanlawson** [comment]
I just checked, and pouchdb-find is 28K min+gz... Also, if you use browserify to bundle everything, then it will take up less space because pouchdb-find actually depends on many of the same modules as PouchDB itself. :)

**Comment by chandu0101** [comment]
28k with gz cool then ! , btw thanks for your awesome work in pouchdb ecosystem :)

**Comment by nolanlawson** [comment]
No prob, happy to help. :)
