### ISSUE TITLE
search function is causing issue on Safari (OS X and iOS)

### ISSUE THREAD

**Issue by nareshbhatia** [nolanlawson/pouchdb-quick-search#27]
Search is working for me very well on Chrome and Firefox. However as soon as I call search on Safari (Mac OS X or iOS), I get this dialog box:

> Allow this website to use space on your disk? The website “http://localhost:3000” is requesting 5 MB of disk space to store “_pouch_glossary-search-41aedf802eabccbf360b0ea56f611df1” as a database on your disk. Currently, this website is allowed to use 5 MB of disk space.

When I click "Allow" the dialog box goes away and then comes back up again and again. This happens for about 20 times and when the dialog box finally goes away, the search index has not been created.

Here's the relevant code:

    return db.search({
        fields: ['name', 'tags'],
        build: true
    });

**Comment by nolanlawson** [comment]
Yup, this is a classic Safari problem. Please read this: http://pouchdb.com/errors.html#not_enough_space

**Comment by nareshbhatia** [comment]
Thanks @nolanlawson - I am up and running on Safari! BTW, is there any way to delete the WebSQL databases on Mac OS and iOS? I was searching the net and couldn't find anything easy.

**Comment by nolanlawson** [comment]
It is not possible. That's why we do a "soft" delete in PouchDB.
