### ISSUE TITLE
How can I search by '_id' ?

### ISSUE THREAD

**Issue by mrded** [nolanlawson/pouchdb-quick-search#28]
Like bellow: 

        db.search({
          query: 'foo',
          fields: ['_id'],
          include_docs: true
        });

**Comment by nolanlawson** [comment]
To search by _id, you should use the `allDocs()` API. It's already indexed by _id. :)

**Comment by nolanlawson** [comment]
You can do prefix searches and exact matches, but that's it: https://github.com/nolanlawson/pouchdb-quick-search#autosuggestions-and-prefix-search

**Comment by mrded** [comment]
@nolanlawson, thanks.

**Comment by mrded** [comment]
Unfortunately that's doesn't allow me to find 'foobarbaz' word by 'bar' keyword. You need to search by full words.

**Comment by nolanlawson** [comment]
yep, that is true. you cannot do suffix or infix searches in pouchdb, because of how indexes work. in fact, even in SQL databases like MySQL, it will do an inefficient table scan when you try to do `LIKE '%foo'`. You can do an inefficient full table scan in PouchDB as well by just doing `allDocs()` and then filtering in-memory.

**Comment by dhavalkakkad** [comment]
Is it possible that I can search all the `_id`  having value less than or equal to 10 ?

I am working with this plugin in my first offline app but not able to find some query parameters here. I just found nolanlawson/pouchdb-find plugin of yours.  Not sure should I switch or use both ?

Any suggestions @nolanlawson ?

**Comment by nolanlawson** [comment]
_ids are always strings, so unfortunately the only way to do this would be to ensure that _ids are encoded like e.g. `00000001` and `00000002`.
