### ISSUE TITLE
angular-js search

### ISSUE THREAD

**Issue by astutesoftware** [nolanlawson/pouchdb-quick-search#31]
I have the search in my angular js controller
I do get the results fine.
However my angular template does not get passed the results.

I am updating the scope variable in the .then() function.

Is there an other event i have to use?

**Comment by astutesoftware** [comment]
adding $rootScope.$apply() ; helped make it work.
is this ok or something is missing?

**Comment by nolanlawson** [comment]
Nope, that's a common fix for Angular integration with PouchDB.
