### ISSUE TITLE
Index fields from nested array of objects?

### ISSUE THREAD

**Issue by nnarhinen** [nolanlawson/pouchdb-quick-search#32]
Given a document like:

``` json
{
  "some_field": "foo",
  "meta": [
    {
       "nested": "First meta"
    },
    {
      "nested": "Second meta"
     }]
}
```

How can I index the "First meta" and "Second meta" values? I tried `meta.nested` and `meta[].nested` but they do not seem to work.

**Comment by nolanlawson** [comment]
Sorry, I did not implement deep fields for this plugin. A PR for something like `meta[0].nested` would be welcome, though! :)
