### ISSUE TITLE
Index fields from nested array of objects

### ISSUE THREAD

**Issue by exoticdevil** [nolanlawson/pouchdb-quick-search#35]
Hello!
Getting problems to serach in nested array with this doc structure

{
   "_id": "1077",
   "_rev": "1-805dcb10756e24f3cf31b5eaf826a430",
   "updated": "0",
   "name": "Swegon",
   "persons": [
       {
           "firstname": "Henrik",
           "person_id": "2005",
           "lastname": "Bork",
           "updated": "1319029129",
       },
       {
           "firstname": "Ernst Børge",
           "person_id": "2006",
           "lastname": "Johansen",
           "updated": "0",
       },
       {
           "firstname": "Leif",
           "person_id": "2463",
           "lastname": "Hamrebø",
           "updated": "0",

       }
   ]
}

Search would work with first array item like firstname, but will not work with others like person_id or lastname.

Querry:
var opts = {
            fields: ['persons[].lastname'],
            query: 'Johansen'
};

**Comment by nolanlawson** [comment]
Instead of `persons[].lastname` I believe it should be just `persons.lastname`.

**Comment by nolanlawson** [comment]
Oh wait nevermind sorry, the issue is that we don't support nested arrays. #33
