### ISSUE TITLE
Query with utf-8

### ISSUE THREAD

**Issue by Buminta** [nolanlawson/pouchdb-quick-search#36]
Hi.
I've problems with search. Hope any body help me!
- With Utf-8:
I'm convert string to search to latin1 for search to search all docs same it.

example:
``` javascript
{query: "nguyễn",
fields: ["display_name"],
highlighting: true,
include_docs: true}
```
however: i've docs with ```display_name``` is ```nguyen``` or ```nguyễn```. And i want to list all this.

- Like ```LIKE query in mysql```:

example:
``` javascript
{query: "%guye%",
fields: ["display_name"],
highlighting: true,
include_docs: true}
```
and i want to show all docs with between is ```guye```
example: ```nguyễn, nguyen, nguye, guyen ...```

Thanks for watching!

**Comment by nolanlawson** [comment]
pouchdb-quick-search defers to lunr.js for any string tokenization and stuff like that; so you might want to look in their repo to see if they have docs on latin1 vs. utf8. In general I would recommend using utf8 everywhere if you can.

Also this module is not really designed for the kind of query you describe (substrings); it's instead optimized for natural language tokenization, e.g. "runs" -> "ran", "run", "running", etc. If you need finer-grained character-by-character control, I recommend PouchDB's `query()` API (map/reduce) or `pouchdb-find`.

**Comment by Buminta** [comment]
thanks for sp.
but i know it. however i don't understand this. i using function for convert from utf8 to latin1 for search. 
example:``` nguyễn -> nguyen```
because ```vietnamese``` can't use like some language.
and i need search with full text search for all words.
so, i need auto search like mysql is ```%guye%``` for searching.

**Comment by nolanlawson** [comment]
If you have custom synonyms that are not supported by the built-in Lunr stemmer (e.g. nguyen == nguyễn), then yeah, that will not work. The basic English porter stemmer only handles English morphology (dogs/dog/dogged/dogging/etc.), and it looks like [lunr-languages](https://github.com/MihaiValentin/lunr-languages) doesn't have support for Vietnamese. Sorry about that!

**Comment by Buminta** [comment]
Thanks for u. I'm trying develop for it with this. I'm learning Lunr Languages.
