### ISSUE TITLE
TypeError: pouch.search is not a function

### ISSUE THREAD

**Issue by yssource** [nolanlawson/pouchdb-quick-search#39]
I try to use this plugin configured with webpack. 

I' m sure the pouchdb. js and this plugin is successfully loaded. 
And according  to your ways, 

var PouchDB = require('pouchdb');
PouchDB.plugin(require('pouchdb-quick-search'));
var pouch = new PouchDB('mydb');
var doc = {_id: 'mydoc', title: "Guess who?", text: "It's-a me, Mario!"};
pouch.search({
 query: 'your query here',
  fields: ['title', 'text']
}).then(function (res) {
  // handle results
}).catch(function (err) {
  // handle error
});

But, error log “TypeError: pouch.search is not a function”. 
Is there anyone using  this plugin successfully with webpack?

**Comment by nolanlawson** [comment]
With Webpack or Browserify, you need to register the plugin yourself. Please see https://github.com/nolanlawson/pouchdb-quick-search#in-nodejsbrowserifywebpack

(I added "Browserify/Webpack" to the title to make it clearer from now on.)
