### ISSUE TITLE
Partial word matching?

### ISSUE THREAD

**Issue by stoplion** [nolanlawson/pouchdb-quick-search#42]
Great plugin. Just curious if partial word matching is available? 

As in, user searches for:
`mega`
and the document title (not _id) is:
 `megaman`

 I know I can handle this with secondary index, just curious if this plugin support this.

**Comment by nolanlawson** [comment]
Sorry, that's not supported by this plugin. This plugin is just for natural-language-style querying (e.g. `dogs`/`dogged`/`dog`/`dogging`/etc.
