### ISSUE TITLE
Can search still work without tokenization or stemming?

### ISSUE THREAD

**Issue by 5amfung** [nolanlawson/pouchdb-quick-search#45]
If I don't care about tokenization or stemming, is it still possible to make search work for languages like Korean, or Chinese.  I thought some kind of simple string match would take place if tokenization and stemming are not used.  But that doesn't seem to be the case when I search for Korean and Chinese.  I didn't get any result back.

Is it just a matter of adding a new language in lunr-languages?

**Comment by nolanlawson** [comment]
Please see my response in #46 ; basically we are dependent upon lunr-languages and the tokenization supports that they provide. If the built-in tokenization does not work for you, then I recommend using normal map/reduce, splitting the string yourself, and `emit()`ing each token.
