### ISSUE TITLE
Multiple languages support?

### ISSUE THREAD

**Issue by 5amfung** [nolanlawson/pouchdb-quick-search#46]
Is it possible?  My database contains multiple languages.  It would be nice to be able to search not just English.

**Comment by nolanlawson** [comment]
Yup, it actually supports a few languages: https://github.com/nolanlawson/pouchdb-quick-search#other-languages

**Comment by 5amfung** [comment]
The ```language``` option can take a single value only.  What if I want to support French, Dutch, or more at the same time?

**Comment by nolanlawson** [comment]
You can do:

```js
pouch.search({
  query: 'marche', 
  fields: ['text_fr'], 
  include_docs: true,
  language: 'fr'
});
```

and

```js
pouch.search({
  query: 'walk', 
  fields: ['text_en'], 
  include_docs: true,
  language: 'en'
});
```

**Comment by 5amfung** [comment]
Not sure if I understood, I guess ```search()``` needs to know what language the input query is in and I have to choose the right language parameter to do the search?  The problem is that I don't necessarily know what languages the users use and they could also use multiple languages at the same time like searching ```marche walk```.

**Comment by nolanlawson** [comment]
@5amfung In that case, you would need to query multiple times for multiple languages and then join the results together yourself.
