### ISSUE TITLE
Cannot read property 'Promise' of undefined

### ISSUE THREAD

**Issue by AlpineTech** [nolanlawson/pouchdb-quick-search#50]
Running this chrome with PouchDb 5.4.4.  Got the latest search dist.

**Comment by jaroslavgorner** [comment]
window.PouchDB.utils.Promise; replace please with { promise: require('pouchdb-promise') };

https://pouchdb.com/2016/06/06/pouchdb-5.4.0.html PouchDB.utils is depreceated... I will try to create pull request when finished with testing...

**Comment by nolanlawson** [comment]
This is a bug in pouchdb-upsert, inherited through pouchdb-mapreduce-no-ddocs. I'll update and rebuild.

**Comment by nolanlawson** [comment]
OK, this is going to take longer than I thought. In the meantime I recommend using: https://github.com/nolanlawson/pouchdb-legacy-utils

**Comment by nolanlawson** [comment]
fixed in https://github.com/nolanlawson/pouchdb-quick-search/pull/51
