### ISSUE TITLE
Support for regex

### ISSUE THREAD

**Issue by natcohen** [nolanlawson/pouchdb-quick-search#55]
I've tried to pass a regex (with 'igm' flags) without much success... I want to be able to get "Mario" results even if I look for "ario"

Any plan to support it?

**Comment by nolanlawson** [comment]
Regexes are not supported, no. It would be difficult (impossible?) to support them given limitations of Lunr and of the way b-trees work in general. Prefix search is fastest.

**Comment by natcohen** [comment]
@nolanlawson What about partial word matching (not only prefixes)? @jefbarn suggests using tokenizer... is it doable?

**Comment by nolanlawson** [comment]
I don't intend to support that. It would also not be very performant unless you did it all in-memory, becuase of how B-trees work.

**Comment by natcohen** [comment]
@nolanlawson what about accents? Is there anything I can do to ignore accents?

**Comment by nolanlawson** [comment]
You would need to either strip them before indexing, or do two queries - one with, one without.

**Comment by nolanlawson** [comment]
Closing because this is not a feature I intend to support, sorry.
