### ISSUE TITLE
Unable to get language support

### ISSUE THREAD

**Issue by natcohen** [nolanlawson/pouchdb-quick-search#56]
I'm a little bit confused with how to enable language support (in web browser).

I've tried to add the following:

      var idx = lunr(function () {
             this.use(lunr.multiLanguage('en', 'fr'));
      });

But I get the following warning:

     Overwriting existing registered function: lunr-multi-trimmer-en-fr
     Function is not registered with pipeline. This may cause problems when serialising the index.

I tried different things like adding `lunr.Index.load(idx);` but I get another warning (`version mismatch: current 0.7.1 importing undefined`) and I can't even build the index...

Any suggestion would be really appreciated

**Comment by nolanlawson** [comment]
Sorry, this is a new feature that was not written by me. There are unit tests that show how it work; you can look at those and see if they provide insight.
