### ISSUE TITLE
ElasticLunr instead of Lunr

### ISSUE THREAD

**Issue by natcohen** [nolanlawson/pouchdb-quick-search#59]
I came across [this website](http://elasticlunr.com/docs/index.html) and was wondering if it could be implemented instaed of Lunr. It brings more features (such as being able to search specific fields)

**Comment by nolanlawson** [comment]
This seems like an in-memory library, like Lunr. I don't see it comparing to pouchdb-quick-search because we used an on-disk index. Interesting project, though.
