### ISSUE TITLE
Add prefix search

### ISSUE THREAD

**Issue by nolanlawson** [nolanlawson/pouchdb-quick-search#6]
I know I said in the readme that you don't need this for prefix search, but I realize now that you do, because we have the benefit of being case-insensitive.

**Comment by mQckingbird** [comment]
what needs to be done to support this?
for local query's, it supports instant search; which it's what we must aim for. 
the -find selector it's fine; but it needs work to get rid of regular expressions (they tend to slow things down). I'll appreciate some ideas regard this and what can we do (or I).
