### ISSUE TITLE
Rollup compatibility issue

### ISSUE THREAD

**Issue by matheusgarcez** [nolanlawson/pouchdb-quick-search#62]
As discussed in the issue: 
https://github.com/driftyco/ionic/issues/8356

This library has a compatibility issue with Rollup because of a 'strict error' in the "md5-jkmyers" library, which seems to no longer being maintained.

Knowing that, I would like to know if you could change it to the same library used in pouchdb [js-spark-md5] (https://github.com/satazor/js-spark-md5)? Or fork of the "md5-jkmyers" repository and apply the bug fixes to it.

Thank you.

**Comment by nolanlawson** [comment]
I would rather have Rollup fix this issue TBH. Browserify and Webpack have no problems with md5-jkmyers.

**Comment by nolanlawson** [comment]
Ionic is moving away from Rollup to Webpack last I heard FWIW
