### ISSUE TITLE
automatically  fill the db from a text file

### ISSUE THREAD

**Issue by maxlinux2000** [nolanlawson/pouchdb-quick-search#64]
Hi, I want to create a book reader using pouchdb.
As this db is static because the book will not change in the future, this is a operation to do one time.

The idea is to automatically  fill the db, reading the text  from a normal csv file, where each line is a record and the fields are separated form a comma or a dot comma symbol.

Can I connect to db from linux shell?

I think to create a bash script with something like:

```
IPS="\n"
for Line in `cat book.csv`; do
  PouchDBinsertCommad "$Line"
done
```

someone have a solution for that?

regards
MaX

**Comment by nolanlawson** [comment]
PouchDB does not support a command-line interface, sorry.
