### ISSUE TITLE
How select unique results using this plugin

### ISSUE THREAD

**Issue by AnnamrajuSarvani** [nolanlawson/pouchdb-quick-search#75]
Hi,
I have duplicates in my db I want return only distinct records. How to do that? is it possible with this plugin?

**Comment by nolanlawson** [comment]
In Pouch/Couch documents are distinct by `_id`; that's the only uniqueness system.

**Comment by nolanlawson** [comment]
Oh I see you want to _select_ distinct results. You would need to do that yourself in JavaScript unfortunately.

**Comment by AnnamrajuSarvani** [comment]
Ok, Thanks. I want to search in complete document like elastic search with _all with 'and', 'or' and 'not' operators. Is it possible with any plugin in pouchdb?
